version: "3.9"
services:
  db:
    image: timescale/timescaledb:latest-pg15
    environment:
      - POSTGRES_PASSWORD=gli
      - POSTGRES_USER=gli
      - POSTGRES_DB=gli
    volumes:
      - db_data:/var/lib/postgresql/data
  redis:
    image: redis:7
  api:
    build: ./backend
    env_file: .env
    depends_on:
      - db
      - redis
    ports:
      - "8080:8080"
  worker:
    build: ./backend
    command: ["celery", "-A", "backend.tasks.build_indices.celery_app", "worker", "-l", "INFO"]
    env_file: .env
    depends_on:
      - api
      - redis
      - db
  web:
    build: ./frontend
    env_file: .env
    depends_on:
      - api
    ports:
      - "3000:3000"
volumes:
  db_data:
